version: '3'
services:
  node:
#    tty: true
    stdin_open: true
    container_name: voucher
    depends_on:
      - mongo
    build:
      context: .
    ports:
      - "9090:9090"
    volumes:
      - .:/var/code:rw
    entrypoint: './startup.sh'

  mongo:
    image: 'mongo:3.4'
