version: '3'
services:
  node:
    tty: true
    stdin_open: true
    container_name: voucher
    #    env_file:
    #    - ./.env
    depends_on:
      - mongo
    build:
      context: .
    volumes:
      - .:/var/code:rw
    entrypoint: './startup.sh'

  mongo:
    image: 'mongo:3.4'
